CREATE TABLE relay (
    id INTEGER PRIMARY KEY,
    url TEXT NOT NULL,
    read INTEGER NOT NULL DEFAULT 1,
    write INTEGER NOT NULL DEFAULT 1,
    advertise INTEGER NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX url ON relay (url);